# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 03:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chatter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_key', models.CharField(max_length=20, unique=True)),
                ('next_chat_code', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='kunja_menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=10, unique=True)),
                ('lunch', models.TextField()),
                ('dinner', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Skyrounge_menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=10, unique=True)),
                ('lunch', models.TextField()),
                ('dinner', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Student_union_menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('price', models.CharField(max_length=10)),
                ('popular', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Woojung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
                ('running_time', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Woojung_menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=10)),
                ('menu', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='woojung',
            name='menus',
            field=models.ManyToManyField(related_name='type', to='api.Woojung_menu'),
        ),
        migrations.AddField(
            model_name='chat',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat', to='api.Chatter'),
        ),
    ]
