# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 03:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatter',
            name='user_key',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='woojung_menu',
            name='menu',
            field=models.CharField(max_length=100),
        ),
    ]
